### ISSUE TITLE
The setting feature is not work

### ISSUE THREAD

**Issue by Icramss** [basicodemine/Metin-Analizi#1]
# Expected behavior

The settings feature should work

# Actual behavior

Setting feature does not work and does not work

# How to reproduce

- Download app on playstore
- Open the app
- enter the name of the twitter account you want to analyze
![Screenshot_20180530-070503_01.png](https://ipfs.busy.org/ipfs/QmWSASryNzUTtZ7QgQaDVwR4xYv7NXitCa2i1NRtnX6Gpq)

- do ✔️ on 🔲
![Screenshot_20180530-070503_02.png](https://ipfs.busy.org/ipfs/QmR2Pb9xVFcLMTZiNQQJLhZ7CXHHiXM2jYqhGbBVePLVaB)

- then click on ` Baglan `to search
![Screenshot_20180530-070503_03.png](https://ipfs.busy.org/ipfs/QmSPXPnZ7oDaCXoAKSaqKJ1wo3DUyMLbdXacbQ9sUCn5ET)

- Once done, Tap` Devam Et `
![Screenshot_20180530-070503_04.png](https://ipfs.busy.org/ipfs/QmagkyPZCXPjLdqd7aPdHb9gKNvUwtzKwY5RZaecxhjLh5)

- then Tap on 3 dots right side
- Tap setting.
- it does not work

### Device: ONE PLUS 2 OxygenOS Version 3.6.1
Operating System:Android 6.0.1
App Version :2.0

# Recording of the bug

https://youtu.be/uA4wi_UQ8yU

**Comment by basicodemine** [comment]
Yes I know :) You can delete that view.
